### ISSUE TITLE
International Space Apps Hackathon

### ISSUE THREAD

**Issue by FredericJacobs** [HackEPFL/suggestions#2]
We'll be hosting the Space Apps Challenge in April 2013 ! 

[More info](http://spaceappschallenge.org/)

**Comment by pirroh** [comment]
Definitely. Last year was a blast!

**Comment by romac** [comment]
Awesome!

**Comment by FredericJacobs** [comment]
Here's some more information regarding the event : http://cl.ly/LSAp

**Comment by FredericJacobs** [comment]
Nice, we are confirmed as a location 
https://gist.github.com/cfa1d13cbbfe04f780c6

**Comment by pirroh** [comment]
Sweet! Time to ping Oleg as well?

**Comment by FredericJacobs** [comment]
Done.

**Comment by BinaryBrain** [comment]
I knew it!
Awesome!

**Comment by loleg** [comment]
This one is going to be even more amazing! Would <} to be involved, and I know the Space Center is keen to host again. I'm also in touch with the new Paris team, what would you think of getting some video collaboration going in the run up, brainstorm or partner on projects?

**Comment by FredericJacobs** [comment]
@loleg : I guess there will be a group hangout like last year. We can definitely set that up.
.

**Comment by FredericJacobs** [comment]
Hey,
Just a quick update. I had the call with all the leads.

Here is what needs to be done. 

1) Finding local Sponsoring + Rewards

I know the Swiss Space Center could sponsor a little bit last year. We can also ask our contacts at Microsoft or Google to chip in. 

When it comes down to rewards, GitHub will probably be happy to give Silver accounts to the winners. We could also use the money from the sponsoring to make custom rewards. 

2) Reserve the EPFL rooms

@pirroh : Can you proceed for that ? Or do we need PolyProg's help ?

**Comment by pirroh** [comment]
To recap: sponsor found and room already reserved.
GitHub and Lenovo will take care of the "presents" for finalists.
Next issues related to the Space Apps Challenge should go in https://github.com/HackEPFL/events
