### ISSUE TITLE
Hacking the Tuition Fees

### ISSUE THREAD

**Issue by FredericJacobs** [HackEPFL/suggestions#3]
This idea is inspired by [Where does my money go](http://wheredoesmymoneygo.org/bubbletree-map.html#/~/grand-total--2010-).

If EPFL was opening some balance sheets we could easy hack such a representation. It's really easy to build on top of libraries like [d3js](http://d3js.org/).

**Comment by romac** [comment]
+1

**Comment by FredericJacobs** [comment]
It's too late now. Still on the shelve but let's close it for now.
