### ISSUE TITLE
Becoming an EPFL Association

### ISSUE THREAD

**Issue by FredericJacobs** [HackEPFL/suggestions#4]
We may benefit from getting a legal status as an EPFL association. This means that we would get insurance, reputation and other benefits.

**Comment by FredericJacobs** [comment]
@pirroh : What's the status ? I guess we're still waiting for papers to be filed.

**Comment by pirroh** [comment]
Yes, we've found out who to contact, and what we want to ask for (i.e., full-fledged association, but no affiliation with Agepoly, and no permanent space... at least for now).

We'll wait for Vetterli's feedback until Tue morning (he'll be talking about us on the 17/12 meeting) and then send around the official requests.

**Comment by BinaryBrain** [comment]
What are pros and cons if we're becomming an EPFL association?

**Comment by FredericJacobs** [comment]
@pirroh : We would love an update about this :)

**Comment by FredericJacobs** [comment]
@pirroh : 

>  Hey guys,
> we got the formal support from both Vetterli and Urbanke (the current dean ad interim) right before Christmas. Since then, I started to flood with emails and phone calls the responsible of associations.epfl.ch ... they acknowledged our needs, but things are moving crazily slow.
> As soon as I can arrange a meeting in person, I'll let you know.

**Comment by FredericJacobs** [comment]
This is suspended until further notice
