### ISSUE TITLE
Facebook Hackathon

### ISSUE THREAD

**Issue by FredericJacobs** [HackEPFL/suggestions#5]
This event is likely to take place in March (end of the month).

More in the works

**Comment by pirroh** [comment]
Reminder: we should ping Ruth around mid of January.

**Comment by FredericJacobs** [comment]
Assigning it to @pirroh

**Comment by FredericJacobs** [comment]
Time to sign up people : https://www.facebook.com/events/225407220917660/?sid=0.43496397766284645

**Comment by pirroh** [comment]
Yep, looks like we did it :+1:
