### ISSUE TITLE
Opening event

### ISSUE THREAD

**Issue by FredericJacobs** [HackEPFL/suggestions#6]
Current status : Contacting speakers

**Comment by rorist** [comment]
Hi, I think it' shouldn't be related to the association creation, but more focused on getting people interests on the project
What they expect from it, who are interested to commit, etc etc.
And probably be enhanced with an alcoholic catalysis (Sat?) :)

**Comment by FredericJacobs** [comment]
Our opening event will be the Facebook Hackathon !

**Comment by romac** [comment]
Sign up here: https://www.facebook.com/events/225407220917660/
