### ISSUE TITLE
Becoming an association

### ISSUE THREAD

**Issue by FredericJacobs** [HackEPFL/suggestions#8]
We tried to become an  EPFL association but unfortunately the EPFL administration wouldn't acknowledge us. So here we are, becoming a regular Swiss association.

This issue will cover the required parts of it.

Given the association will exist in French Switzerland, the filing of the documents will happen in french.

**Comment by romac** [comment]
Update: That's not true anymore since EPFL reversed their judgement and we're now pretty sure to be able to become an EPFL association. We haven't submitted [our statutes](https://github.com/HackEPFL/administrative/blob/master/statutes.md) yet but we'll try to do so quickly.

**Comment by pirroh** [comment]
"Statutes" has been submitted, and already revised once with the feedback coming from the associations@EPFL people. We're waiting for the (hopefully) last round of feedback.

**Comment by romac** [comment]
We're official :)

**Comment by pirroh** [comment]
Best "Closed" event ever. \o/
